As 2

In [56]:
##Code 1: random bots


import numpy as np
n = 3

rng = np.random.default_rng()



##bot random when no strategy

def botPick(m):
    i = rng.integers(0, n)
    j = rng.integers(0, n)
        
    if m[i, j] == 2:
        return i, j
    else:
        return botPick(m)



##if still not full
def hasTwo(m):
    n = m.shape[0]
    for x in range(n):
        for y in range(n):
            if( m[x,y] == 2 ):
                return True
    return False


                    

def repeat(n):
    global k
    m = 2*np.ones((n,n),int)
    i = rng.integers(0,n)
    j = rng.integers(0,n)
    m[i,j] = 0   ##start zero at a random placea
    while hasTwo(m) == True:
        i, j = botPick(m)
        m[i,j] = 1
        i, j = botPick(m)
        m[i,j] = 0
    if (np.linalg.det(m)) == 0:
        #print(m)   #when you want to see random matrices, use these
        #print()
        k += 1        



def rxtimes(times,n):
    for i in range (times):
        repeat(n)

    print(k)

In [58]:
k = 0
n = 3
rxtimes(1000 , 3)

718


In [ ]:
##this is a try of making the bots more clever, but I didn't use it eventually(and it didn't work lol)
def checkrow(m):
    k = 0
    length = m.shape[0]
    sus = length+1 , length+1
    for i in range(length-1):
        for j in range(length-1):
            if (m[i,j] == 0):
                k = k + 1
                print(k)
        if (k == length-1):
            for l in range(length-1):
                if m[i,l] == 2:
                    sus = i,l
                    break
        k = 0
        
    
    if (sus == length+1 , length+1):
        return False
    else:
        return sus

In [12]:
##Code 2: random bots


import numpy as np
n = 4

rng = np.random.default_rng()



##bot random when no strategy

def botPick(m):
    i = rng.integers(0, n)
    j = rng.integers(0, n)
        
    if m[i, j] == 2:
        return i, j
    else:
        return botPick(m)



##if still not full
def hasTwo(m):
    n = m.shape[0]
    for x in range(n):
        for y in range(n):
            if( m[x,y] == 2 ):
                return True
    return False


                    

def repeat(n):
    global k
    m = 2*np.ones((n,n),int)
   
    while hasTwo(m) == True:
        i, j = botPick(m)
        m[i,j] = 0
        i, j = botPick(m)
        m[i,j] = 1
    if (np.linalg.det(m)) == 0:
        print(m)
        print()
        k += 1        



def rxtimes(times,n):
    for i in range (times):
        repeat(n)

    print(k)

In [13]:
k = 0
n = 4
rxtimes(10 , 4)

[[0 0 0 0]
 [1 0 0 1]
 [0 1 1 1]
 [0 1 1 1]]

[[0 0 0 1]
 [1 0 0 0]
 [0 1 1 1]
 [1 1 1 0]]

[[1 1 1 1]
 [1 0 0 0]
 [1 1 0 1]
 [0 0 0 0]]

[[1 0 0 1]
 [1 1 0 1]
 [1 0 0 0]
 [1 1 0 0]]

[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 1]
 [1 1 1 1]]

[[0 0 0 0]
 [0 1 1 1]
 [1 1 1 0]
 [0 1 1 0]]

6


In [60]:
##Code 3: random bots when start with 1, n = 3


import numpy as np
n = 3

rng = np.random.default_rng()



##bot random when no strategy

def botPick(m):
    i = rng.integers(0, n)
    j = rng.integers(0, n)
        
    if m[i, j] == 2:
        return i, j
    else:
        return botPick(m)



##if still not full
def hasTwo(m):
    n = m.shape[0]
    for x in range(n):
        for y in range(n):
            if( m[x,y] == 2 ):
                return True
    return False


                    

def repeat(n):
    global k
    m = 2*np.ones((n,n),int)
    ##start zero at a random placea
    while hasTwo(m) == True:
        i, j = botPick(m)
        m[i,j] = 1
        if hasTwo(m) == True:
            i, j = botPick(m)
            m[i,j] = 0
    if (np.linalg.det(m)) == 0:
        k += 1        



def rxtimes(times,n):
    for i in range (times):
        repeat(n)

    print(k)

In [64]:
k = 0
n = 3
rxtimes(1000 , 3)

428
